---
# from https://deb.sury.org/
# and
# https://packages.sury.org/php/README.txt

- name: Make sure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - lsb-release
      - ca-certificates
    state: present

- name: Get gpg php repo key
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: Add php source repo to local apt sources
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
    filename: php
