---

- name: Install PHP Xdebug extension
  apt:
    name: php-xdebug
    state: present

- name: Configure Xdebug
  template:
    src: xdebug.ini.tpl
    dest: '{{ php_path }}/mods-available/xdebug.ini'
    mode: 0644
  when: target is not defined or target != 'local'

- name: Configure Xdebug for local
  template:
    src: xdebug_insecure.ini.tpl
    dest: '{{ php_path }}/mods-available/xdebug.ini'
    mode: 0644
  when: target is defined and target == 'local'
