---

- name:  Host {{ target }} provisioning
  hosts: '{{ target }}'
  become: yes

  vars_files:
    - vars/common.yml
    - vars/prod.yml
    - ../vars/prod.yml

  roles:
    - server
    - nginx
    - php
    - apps
    - newrelic
